### ISSUE TITLE
for-loop variable uncovered

### ISSUE THREAD

**Issue by bennn** [florence/cover#107] opened 2015-09-30 03:54 UTC
When I write & test a simple for-loop, the loop var is considered uncovered:
![screen shot 2015-09-29 at 11 53 32 pm](https://cloud.githubusercontent.com/assets/1731829/10184064/5018cf2e-6705-11e5-8933-43b43c8101a5.png)

Adding an `in-list` annotation improves my coverage.
![screen shot 2015-09-29 at 11 53 46 pm](https://cloud.githubusercontent.com/assets/1731829/10184073/5b09627c-6705-11e5-9c57-cf571573bf0c.png)

**Comment by rpless** [comment] 2015-09-30 12:25
Hi @bennn. I believe this duplicates #27. 
The issue is currently documented in the [Gotcha's section](http://pkg-build.racket-lang.org/doc/cover/basics.html#%28part._.Gotcha_s%29).

**Comment by florence** [comment] 2015-09-30 13:51
Yes, this is a known bug in the for loop library. I've tried to fix it but that code is such a tangled nest of macro's and can't figure out why the srcloc gets erased in the first place.

I should probably actually log a bug about that...

**Comment by florence** [comment] 2015-09-30 13:52
There, logged at racket/racket#1077

I'm going to close this as a duplicate.

**Closed** 2015-09-30 14:36 UTC
Labels: duplicate

**Comment by bennn** [comment] 2015-09-30 17:50
@rpless Gotcha! @florence Thanks for passing the blame

**Comment by florence** [comment] 2015-09-30 18:10
@bennn Blame is still mine, turns out its an errortrace bug that I get to fix :P
