### ISSUE TITLE
Doesn't work on directories with subdirectories.

### ISSUE THREAD

**Issue by samth** [florence/cover#20] opened 2015-01-12 14:51 UTC
```
open-input-file: cannot open directory as a file
  path: /home/samth/sw/plt/extra-pkgs/compiler/.
  system error: errno=?
  context...:
   /home/samth/sw/plt/racket/collects/setup/unpack.rkt:40:0: fold-plt-archive
   /home/samth/sw/plt/extra-pkgs/compiler/compiler-lib/compiler/commands/unpack.rkt:39:0: for-loop
   /home/samth/sw/plt/extra-pkgs/compiler/compiler-lib/compiler/commands/unpack.rkt: [running body]
   /home/samth/sw/plt/racket/share/pkgs/cover/cover.rkt:34:4: for-loop
   /home/samth/sw/plt/racket/share/pkgs/cover/cover.rkt:24:0: test-files!3
   (submod /home/samth/sw/plt/racket/share/pkgs/cover/raco.rkt main): [running body]
```

**Comment by florence** [comment] 2015-01-12 15:08
What is the exact command you ran?

**Comment by samth** [comment] 2015-01-12 15:09
`raco cover compiler-test`

**Comment by florence** [comment] 2015-01-12 15:24
Thats odd, I see different behavior (The same behavior noted in Issue #21). Is either `compiler` or `compiler-test` a symlink?

**Comment by samth** [comment] 2015-01-12 15:48
Try `raco cover .` in `compiler`.

**Comment by florence** [comment] 2015-01-12 16:09
I think this is a duplicate of #18 and possibly #4,  given that compiler-lib/compiler/commands/unpack.rkt uses `command-line`

**Closed** 2015-01-14 02:43 UTC
Labels: duplicate
