### ISSUE TITLE
Error when generating coverage on a Typed Racket project

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#97] opened 2015-08-30 03:08 UTC
I've just created a new package, [Envy](https://github.com/lexi-lambda/envy), but running cover on it fails with the following error:

```
generating test coverage for ("/Users/alexis/gits/racket/envy/envy/environment.rkt" "/Users/alexis/gits/racket/envy/envy/info.rkt" "/Users/alexis/gits/racket/envy/envy/main.rkt" "/Users/alexis/gits/racket/envy/envy/private/coerce.rkt" "/Users/alexis/gits/racket/envy/envy/scribblings/envy.scrbl" "/Users/alexis/gits/racket/envy/envy/scribblings/envy.scrbl~" "/Users/alexis/gits/racket/envy/info.rkt" "/Users/alexis/gits/racket/envy/tests/envy/environment.rkt")
dumping coverage info into "coverage"
cover: no coverage information for "/Users/alexis/gits/racket/envy/envy/private/coerce.rkt"
  context...:
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/format-utils.rkt:25:0: make-covered?
   /Users/alexis/gits/racket/racket/racket/collects/racket/private/more-scheme.rkt:374:13: hash-ref!
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/cover.rkt:276:5
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:369:4: recur
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:346:0: expression-coverage/file
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:113:0: make-html-file
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:47:4: for-loop
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:45:0: get-files
   /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/private/html/html.rkt:29:0: generate-html-coverage
   (submod /Users/alexis/gits/racket/racket/racket/share/pkgs/cover/raco.rkt main): [running body]
   /Users/alexis/gits/racket/racket/racket/collects/raco/raco.rkt: [running body]
   /Users/alexis/gits/racket/racket/racket/collects/raco/main.rkt: [running body]
```

Is this a cover bug?

**Comment by florence** [comment] 2015-08-30 12:20
This error *should* be fixed on the current git HEAD. Im not near a laptop right now, but I'll double check when I am.

**Comment by florence** [comment] 2015-08-30 17:33
Confirmed. This bug is fixed on cover's git HEAD. I probably wont be able to merge that commit for at least a week, because the new changes are breaking. 

The work around would be to use cover from git HEAD.

If you are using cover for coveralls then your `.travis.yaml` file needs to install the `cover-coveralls` package *after* cover is installed from git HEAD. (This is part of the breaking changes I mentioned; Cover's repository has split).

I'm closing this issue issue for now. When the next release happens (which will contain this fix) I'll announce it on the racket mailing list.

**Closed by florence** 2015-08-30 17:33 UTC

**Comment by lexi-lambda** [comment] 2015-08-30 18:22
Sure thing, no problem, sounds like the changes are all good! :+1: 

I'll save you my usual rant about how the package system is broken (if it had actual *versioning*, this wouldn't be a problem!), since I suppose I'd be preaching to the choir. :wink: Glad to hear this is already fixed, though.
